everyvalue-web/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :subjects do
    collection do
      get 'comment'
    end
  end
  resources :valuations
  resources :hashtags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subject_attachments

  root 'root#home'
end

everyvalue-web/app/models/subject_attachment.rb
class SubjectAttachment < ApplicationRecord
  belongs_to :subject

  #for using carrierwave
  mount_uploader :content, ContentUploader
end

everyvalue-web/app/controllers/subject_attachments_controller.rb
class SubjectAttachmentsController < ApplicationController
  before_action :set_subject_attachment, only: [:show, :edit, :update, :destroy]

  # GET /subject_attachments
  # GET /subject_attachments.json
  def index
    @subject_attachments = SubjectAttachment.all
  end

  # GET /subject_attachments/1
  # GET /subject_attachments/1.json
  def show
  end

  # GET /subject_attachments/new
  def new
    @subject_attachment = SubjectAttachment.new
  end

  # GET /subject_attachments/1/edit
  def edit
  end

  # POST /subject_attachments
  # POST /subject_attachments.json
  def create
    puts "params : #{params}"
    puts "subject_attachment_params : #{subject_attachment_params}"

    @subject_attachment = SubjectAttachment.new(subject_attachment_params)

    puts "content : #{@subject_attachment.content}"

    # render text: 'http://naver.com'
    render json: { url: @subject_attachment.content, content_id: @subject_attachment.id } if @subject_attachment.save

    # respond_to do |format|
    #   if @subject_attachment.save
    #     format.html { redirect_to @subject_attachment, notice: 'Subject attachment was successfully created.' }
    #     format.json { render :show, status: :created, location: @subject_attachment }
    #     render text: @subject_attachment.content
    #   else
    #     format.html { render :new }
    #     format.json { render json: @subject_attachment.errors, status: :unprocessable_entity }
    #     render text: 'http://www.naver.com'
    #   end
    # end
  end

  # PATCH/PUT /subject_attachments/1
  # PATCH/PUT /subject_attachments/1.json
  def update
    respond_to do |format|
      if @subject_attachment.update(subject_attachment_params)
        format.html { redirect_to @subject_attachment, notice: 'Subject attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject_attachment }
      else
        format.html { render :edit }
        format.json { render json: @subject_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subject_attachments/1
  # DELETE /subject_attachments/1.json
  def destroy
    @subject_attachment.destroy
    respond_to do |format|
      format.html { redirect_to subject_attachments_url, notice: 'Subject attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject_attachment
      @subject_attachment = SubjectAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_attachment_params
      params.require(:subject_attachment).permit(:subject_id, :content)
    end
end

everyvalue-web/app/helpers/subject_attachments_helper.rb
module SubjectAttachmentsHelper
end

everyvalue-web/app/views/subject_attachments/_form.html.erb
<%= form_with(model: subject_attachment, local: true) do |form| %>
  <% if subject_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject_attachment.errors.count, "error") %> prohibited this subject_attachment from being saved:</h2>

      <ul>
      <% subject_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.text_field :subject_id, id: :subject_attachment_subject_id %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :subject_attachment_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

everyvalue-web/app/views/subject_attachments/edit.html.erb
<h1>Editing Subject Attachment</h1>

<%= render 'form', subject_attachment: @subject_attachment %>

<%= link_to 'Show', @subject_attachment %> |
<%= link_to 'Back', subject_attachments_path %>

everyvalue-web/app/views/subject_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subject Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subject_attachments.each do |subject_attachment| %>
      <tr>
        <td><%= subject_attachment.subject %></td>
        <td><%= subject_attachment.content %></td>
        <td><%= link_to 'Show', subject_attachment %></td>
        <td><%= link_to 'Edit', edit_subject_attachment_path(subject_attachment) %></td>
        <td><%= link_to 'Destroy', subject_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject Attachment', new_subject_attachment_path %>

everyvalue-web/app/views/subject_attachments/new.html.erb
<h1>New Subject Attachment</h1>

<%= render 'form', subject_attachment: @subject_attachment %>

<%= link_to 'Back', subject_attachments_path %>

everyvalue-web/app/views/subject_attachments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @subject_attachment.subject %>
</p>

<p>
  <strong>Content:</strong>
  <%= @subject_attachment.content %>
</p>

<%= link_to 'Edit', edit_subject_attachment_path(@subject_attachment) %> |
<%= link_to 'Back', subject_attachments_path %>