everyvalue-web/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :subjects do
    collection do
      get 'comment'
    end
  end
  resources :valuations
  resources :hashtags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subject_attachments

  root 'root#home'
end

everyvalue-web/app/models/valuation.rb
class Valuation < ApplicationRecord
  belongs_to :subject
  belongs_to :user
end

everyvalue-web/app/controllers/valuations_controller.rb
class ValuationsController < ApplicationController
  before_action :set_valuation, only: [:show, :edit, :update, :destroy]

  # GET /valuations
  # GET /valuations.json
  def index
    @valuations = Valuation.all
  end

  # GET /valuations/1
  # GET /valuations/1.json
  def show
  end

  # GET /valuations/new
  def new
    @valuation = Valuation.new
  end

  # GET /valuations/1/edit
  def edit
  end

  # POST /valuations
  # POST /valuations.json
  def create
    @valuation = Valuation.new(valuation_params)

    if @valuation.save
      render json: nil
    else
      render json: nil
    end
  end

  # PATCH/PUT /valuations/1
  # PATCH/PUT /valuations/1.json
  def update
    respond_to do |format|
      if @valuation.update(valuation_params)
        format.html { redirect_to @valuation, notice: 'Valuation was successfully updated.' }
        format.json { render :show, status: :ok, location: @valuation }
      else
        format.html { render :edit }
        format.json { render json: @valuation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valuations/1
  # DELETE /valuations/1.json
  def destroy
    @valuation.destroy
    respond_to do |format|
      format.html { redirect_to valuations_url, notice: 'Valuation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valuation
      @valuation = Valuation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def valuation_params
      params.require(:valuation).permit(:subject_id, :user_id, :user_nickname, :price)
    end
end

everyvalue-web/app/helpers/valuations_helper.rb
module ValuationsHelper
end

everyvalue-web/app/views/valuations/_form.html.erb
<%= form_with(model: valuation, local: true) do |form| %>
  <% if valuation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(valuation.errors.count, "error") %> prohibited this valuation from being saved:</h2>

      <ul>
      <% valuation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.text_field :subject_id, id: :valuation_subject_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :valuation_user_id %>
  </div>

  <div class="field">
    <%= form.label :user_nickname %>
    <%= form.text_field :user_nickname, id: :valuation_user_nickname %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :valuation_price %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

everyvalue-web/app/views/valuations/edit.html.erb
<h1>Editing Valuation</h1>

<%= render 'form', valuation: @valuation %>

<%= link_to 'Show', @valuation %> |
<%= link_to 'Back', valuations_path %>

everyvalue-web/app/views/valuations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Valuations</h1>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>User</th>
      <th>User nickname</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @valuations.each do |valuation| %>
      <tr>
        <td><%= valuation.subject %></td>
        <td><%= valuation.user %></td>
        <td><%= valuation.user_nickname %></td>
        <td><%= valuation.price %></td>
        <td><%= link_to 'Show', valuation %></td>
        <td><%= link_to 'Edit', edit_valuation_path(valuation) %></td>
        <td><%= link_to 'Destroy', valuation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Valuation', new_valuation_path %>

everyvalue-web/app/views/valuations/new.html.erb
<h1>New Valuation</h1>

<%= render 'form', valuation: @valuation %>

<%= link_to 'Back', valuations_path %>

everyvalue-web/app/views/valuations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @valuation.subject %>
</p>

<p>
  <strong>User:</strong>
  <%= @valuation.user %>
</p>

<p>
  <strong>User nickname:</strong>
  <%= @valuation.user_nickname %>
</p>

<p>
  <strong>Price:</strong>
  <%= @valuation.price %>
</p>

<%= link_to 'Edit', edit_valuation_path(@valuation) %> |
<%= link_to 'Back', valuations_path %>