everyvalue-web/config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }
  resources :subjects do
    collection do
      get 'comment'
    end
  end
  resources :valuations
  resources :hashtags
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :subject_attachments

  root 'root#home'
end

everyvalue-web/app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :hashtags
  has_many :subject_attachments, dependent: :destroy
  has_many :valuations
  has_many :comments

  accepts_nested_attributes_for :subject_attachments, reject_if: proc { |attributes| attributes[:name].blank? }, allow_destroy: true

  def self.ransackable_attributes(auth_object = nil)
    #title_or_contents 이거는 type nil class 에러가 나고 있어서 일단 지움..
    %w(title contents user_nickname)
  end
end

everyvalue-web/app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_navbar_data, only: [:index, :show, :new, :edit]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :current_user, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :set_subject, only: [:show, :edit, :update, :destroy]
  before_action :set_hashtag_id, only: [:create, :update]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
    @comments = @subject.comments

    if @current_user
      @user_id = @current_user.id
      @user_nickname = @current_user.nickname
      user_valuation = @subject.valuations.where(user_id: @current_user.id).first
      @user_value_on_subject = user_valuation.price if user_valuation.present?
    end

    # replies = Reply.where(id: @comments.map(&:id))
    # @comments.each do |c|
    #   c.searched_replies = replies.select { |r| r.comment_id == c.id }
    # end
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
    @subject_attachment = @subject.subject_attachments.build
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    puts params
    puts subject_params

    @subject = Subject.new(subject_params)
    @subject.user = @current_user
    @subject.user_nickname = @current_user.nickname

    respond_to do |format|
      if @subject.save
        HashtagsSubject.create(hashtag_id: @hashtag_id, subject_id: @subject.id)
        subject_attachments = params[:subject_attachments]
        if subject_attachments.present?
          subject_attachments.each do |id|
            subject_attachment = SubjectAttachment.find_by_id(id)
            if subject_attachment.present? && @subject.contents.include?(URI.encode(subject_attachment.content.file.filename))
              subject_attachment.update_column(:subject_id, @subject.id)
            end
          end
        end

        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def comment
  #   @comments = Subject.find(1).comments
  #
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    def set_hashtag_id
      @hashtag_id = params[:subject][:hashtag_id]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:title, :contents, :user_id, :user_nickname, :average_value)
    end
end

everyvalue-web/app/helpers/subjects_helper.rb
module SubjectsHelper
  def hashtags_options
    Hashtag.all
    # Hashtag.all.map(&:name)
  end
end

everyvalue-web/app/views/subjects/_comment.html.erb
<li class="commentLi" data-commentid="<%= comment.id %>" style="margin-left: calc(0px + 48*<%= comment.depth %>px);">
  <table class="form-comments-table">
    <tr>
      <td>
        <% if comment.parent.present? %>
            <img id="img-reply-arrow" src="/assets/img_back_btn.png" />
        <% end %>
      </td>
      <td><div class="comment-user"><%= comment.user_nickname %></div></td>
      <td><div class="comment-timestamp"><%= comment.updated_at %></div></td>
      <td>
        <div id="comment-<%= comment.id %>" data-commentid="<%= comment.id %>" class="comment comment-step<%= comment.id %>" >
          <%= comment.contents %>
          <div id="commentactions-<%= comment.id %>" class="comment-actions">
            <div class="input-group input-group-sm" role="group">
              <input type="text" class="form-control" placeholder="답글을 입력하세요." aria-describedby="sizing-addon3" id="reply-text-<%= comment.id %>" data-commentid="<%= comment.id %>">
              <span class="input-group-btn">
                <button type="button" class="btn btn-primary btn-sm" id="reply-to-<%= comment.id %>" data-commentid="<%= comment.id %>"><i class="fa fa-edit"></i>답글</button>
                <% if comment.user_id == @user_id %>
                  <button type="button" class="btn btn-default btn-sm"><i class="fa fa-pencil"></i>수정</button>
                  <button type="button" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i >삭제</button>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      </td>
    </tr>
  </table>
  <% if comment.children.present? %>
      <% comment.children.each do |child| %>
          <%= render partial: 'subjects/comment', locals: { comment: child } %>
      <% end %>
  <% end %>
</li>

everyvalue-web/app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true, html: { multipart: true }) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, 'error') %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>카테고리</label><br>
    <select id="select_hashtag" class="selectpicker" title="평가 카테고리를 고르세요">
      <% hashtags_options.each do |hashtag| %>
          <option value="<%= hashtag.id %>"> <%= hashtag.name %></option>
      <% end %>
    </select>
    <input type="hidden" name="subject[hashtag_id]" id="subject_hashtag_id"/>
  </div>

  <div class="form-group">
    <%= form.label :title, '제목' %>
    <%= form.text_field :title, id: :subject_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :contents, '내용' %>
    <%= form.text_area :contents, id: :subject_contents, data: { upload_url: subject_attachments_path }, class: 'form-control' %>
  </div>

  <div id="subject_attachment_id" style="display:none;"></div>
  <div class="actions">
    <%= form.submit '저장하기', class: 'btn btn-success' %>
  </div>
<% end %>

everyvalue-web/app/views/subjects/comment.html.erb
<div class="chatContainer">
  <div class="chatTitleContainer">댓글</div>
  <div class="chatHistoryContainer">
    <ul class="formComments">
      <% @comments.each do |comment| %>
          <%= render partial: 'subjects/comment', locals: {comment: comment } %>
      <% end %>
    </ul>
  </div>

  <div class="input-group input-group-sm chatMessageControls">
    <span class="input-group-addon" id="sizing-addon3">Comment</span>
    <input type="text" class="form-control" placeholder="Type your message here.." aria-describedby="sizing-addon3">
    <span class="input-group-btn">
            <button id="clearMessageButton" class="btn btn-default" type="button">Clear</button>
            <button id="sendMessageButton" class="btn btn-primary" type="button"><i class="fa fa-send"></i>Send</button>
        </span>
    <span class="input-group-btn">
            <button id="undoSendButton" class="btn btn-default" type="button" disabled><i class="fa fa-undo"></i>Undo</button>
        </span>
  </div>
</div>

everyvalue-web/app/views/subjects/edit.html.erb
<div class="container">
  <div class="row">
    <%= render 'form', subject: @subject %>
  </div>
  <div class="row">
    <%= link_to 'Show', @subject %> | <%= link_to 'Back', subjects_path %>
  </div>
</div>

everyvalue-web/app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Contents</th>
      <th>User</th>
      <th>User nickname</th>
      <th>Average value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.title %></td>
        <td><%= subject.contents %></td>
        <td><%= subject.user %></td>
        <td><%= subject.user_nickname %></td>
        <td><%= subject.average_value %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

everyvalue-web/app/views/subjects/new.html.erb
<div class="container">
  <div class="row">
    <%= render 'form', subject: @subject %>
  </div>
  <div class="row">
    <%= link_to 'Back', subjects_path %>
  </div>

</div>

everyvalue-web/app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container subjectContainer">
  <div class="row">
    <p>
      <%= @subject.title %>
      <%= @subject.user_nickname %>
    </p>

    <p>
      <%= @subject.contents.html_safe %>
    </p>
  </div>
  <div class="row">
    <div class="valuationContentsContainer">
      <% if @user_value_on_subject.present? %>
          <div class="row text-center valuation-text">
            현재 <%= @subject.title %> 의 평가액은 <span style="color:red;"><%= @subject.average_value %></span> 원 입니다.
          </div>
          <div class="row text-center valuation-text">
            당신의 평가액은 <span style="color:red;"><%= @user_value_on_subject %></span> 원 입니다.
          </div>
      <% else %>
          <div class="row">
            <div class="col-lg-12 col-xl-12">
              <div class="row">
                <div class="text-center valuation-text">
                  현재 <%= @subject.title %>의 평가액은 평가 후 볼 수 있습니다.
                </div>
              </div>
              <div class="row" style="margin-left:20px; margin-right:20px;">
                <div class="col-lg-6 col-xl-6 text-center valuation-text">
                  당신이 생각하는 <%= @subject.title %>의 평가액은?
                </div>
                <div class="col-lg-6 col-xl-6">
                  <div class="form-group" style="margin-top: 15px;">
                    <div class="input-group">
                      <span class="input-group-addon">￦</span>
                      <input type="number" class="form-control" placeholder="평가액(자연수만 입력가능)" min="1" step="1" pattern="^[1-9]\d*$" id="input-subject-value" />
                      <span class="input-group-btn">
                      <button type="button" class="btn btn-success" id="submit-subject-value">입력</button>
                    </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
  <div class="row">
    <!--<div class="chatTitleContainer">댓글</div>-->
    <div class="chatHistoryContainer">
      <ul class="formComments">
        <% @comments.each do |comment| %>
            <%= render partial: 'subjects/comment', locals: { comment: comment } %>
        <% end %>
      </ul>
    </div>

    <!-- 내 댓글 다는 영역 -->
    <div class="input-group input-group-sm chatMessageControls">
      <span class="input-group-addon" id="sizing-addon3">댓글 작성</span>
      <input type="text" class="form-control" placeholder="내용을 입력하세요." aria-describedby="sizing-addon3" id="commentText">
      <span class="input-group-btn">
      <!--<button id="clearMessageButton" class="btn btn-default" type="button">초기화</button>-->
      <button id="sendMessageButton" class="btn btn-primary" type="button"><i class="fa fa-send"></i>저장</button>
    </span>
      <!--<span class="input-group-btn">-->
      <!--<button id="undoSendButton" class="btn btn-default" type="button" disabled><i class="fa fa-undo"></i>취소</button>-->
      <!--</span>-->
    </div>
  </div>
</div>
<!-- 평가 영역 -->
<!-- 현재 해당 subject의 평가액이 노출되는 영역 -->
<!--<div class="valuationContainer">-->
<!--</div>-->

<!-- 댓글 영역 -->
<!-- 댓글 목록 -->
<!--<div class="chatContainer">-->
<!--</div>-->
<div class="container">
  <%= link_to 'Edit', edit_subject_path(@subject) %> |
  <%= link_to 'Back', subjects_path %>
</div>
<textarea id="textarea-subject-id" style="display:none;"><%= @subject.id %></textarea>
<textarea id="textarea-user-id" style="display:none;"><%= @user_id %></textarea>
<textarea id="textarea-user-nickname" style="display:none;"><%= @user_nickname %></textarea>
<textarea id="textarea-user-value" style="display:none;"><%= @user_value_on_subject %></textarea>